### ISSUE TITLE
[RSR-498] - XML nodes creation order has to be fixed

### ISSUE THREAD

**Issue by DamienPERNET** [com-pas/compas-sct#105]
US [RSR-367](https://github.com/com-pas/compas-sct/issues/66) creates XML nodes.
But these XML nodes created don't respect the order given by XSD demands.

- Could you fix XML nodes order by using file given in attachement ?
- The output file has to fulfill the XSD validation and check this validation

**Comment by samirromdhani** [comment]
I think the order is correct, verified by @AliouDIAITE today.
