### ISSUE TITLE
Create Actions to update automatically java docs

### ISSUE THREAD

**Issue by AliouDIAITE** [com-pas/compas-sct#159]
**User Story**

As a developer

I want to update javadoc automatically when code is pushed.
See example: https://github.com/com-pas/compas-sct/blob/develop/.github/workflows/automate_javadoc.yml

So that the github page is update with new javadoc

**Acceptance criteria**
javadoc updated with functionality documentation for code added or deleted.

**Comment by samirromdhani** [comment]
Hi @AliouDIAITE, @SaintierFr 

Can read this PR ?

I will go into some detail. 

> To automatically update the javadoc: when a developer creates a pull request to **develop**  and thinks that javadoc needs to be updated after it has been merged, the developer must have already set the label **javadoc** in her PR.
After her PR is merged, _automate_javadoc.yml_ is triggered, which leads to the creation of a new PR from 
_depondabot_ to the **gh-pages** branch and it's automatically assigned to the author of the merged one.
As a result the gh-pages deployment is ready to update javadoc once he accepts the _depondabot_ PR.

> I also mentioned that **gh-pages** actually doesn't have a documentation folder (docs), this need https://github.com/com-pas/compas-sct/pull/228

**Comment by samirromdhani** [comment]
@AliouDIAITE 
As discussed. I skipped creating a PR and simply pushed the `gh-pages` branch.
