### ISSUE TITLE
[RSR-630] - Automated process for Dataset and CB creation and Extref update - Creation of MAC Address and other network properties for SV and GOOSE Control Blocks - Part 6/6

### ISSUE THREAD

**Issue by DamienPERNET** [com-pas/compas-sct#232]
<html>
<body>
<p><strong>Context:</strong></p>
<p>In a SCD file, all GOOSE and SampledValue Control Blocks must have Network settings.</p>
<p>Thus, all GOOSE and SampledValue Control Blocks shall have one MAC Address and one VLANID assigned among other settings such as:</p>
<ul>
<li>VLAN - PRIORITY</li>
<li>APPID</li>
<li>MAC Address</li>
<li>VLANID</li>
<li>some Timers limits for GOOSE CB only</li>
</ul>
<p>&nbsp;</p>
<p><strong>US purpose:</strong></p>
<p>The US purpose is to define these Network settings for GOOSE and SampledValue Control Blocks</p>
<p>&nbsp;</p>
<p><strong>Prerequisites:</strong></p>
<ul>
<li>US&nbsp;<a class="issue-link" title="COMPAS - Service to extract ExtRef signals with all their properties to bind automatically Active or Untested Bay Internal or External ExtRef signals - Part 1/3" href="https://gopro-tickets.rte-france.com/browse/RSR-398" data-issue-key="RSR-398"><del>RSR-398</del></a>&nbsp;and&nbsp;<a class="issue-link" title="COMPAS - Service to extract ExtRef signals with all their properties to bind automatically Bay Internal or External ExtRef signals - Part 2/3" href="https://gopro-tickets.rte-france.com/browse/RSR-473" data-issue-key="RSR-473"><del>RSR-473</del></a>&nbsp;have already been developed to list all ExtRef signals with their attributes and properties</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS - Automated process for DataSet and CB creation and ExtRef update - Filter to keep only Active or Untested Bay Internal or External ExtRef signals and group them to do Dataset - Part 1/6" href="https://gopro-tickets.rte-france.com/browse/RSR-389" data-issue-key="RSR-389"><del>RSR-389</del></a>&nbsp;has already been developed because it is the first part of the service</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS - Automated process for Dataset and CB creation and Extref update - DataSet creation - Part 2/6" href="https://gopro-tickets.rte-france.com/browse/RSR-433" data-issue-key="RSR-433"><del>RSR-433</del></a>&nbsp;has already been developed because it is the second part of the service</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS - Automated process for Dataset and CB creation and Extref update - Control Block creation - Part 3/6" href="https://gopro-tickets.rte-france.com/browse/RSR-434" data-issue-key="RSR-434"><del>RSR-434</del></a>&nbsp;has already been developed because&nbsp;it is the third part of the service</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS - Automated process for Dataset and CB creation and Extref update - ExtRef.srcXXXXX update - Part 4/6" href="https://gopro-tickets.rte-france.com/browse/RSR-435" data-issue-key="RSR-435"><del>RSR-435</del></a>&nbsp;has already been developed because&nbsp;it is the fourth part of the service</li>
<li>US <a class="issue-link" title="COMPAS - Automated process for Dataset and CB creation and ExtRef update - The previously created Data groups are analysed to be processed or rejected - Part 5/6" href="https://gopro-tickets.rte-france.com/browse/RSR-607" data-issue-key="RSR-607">RSR-607</a> has already been developed because it is the fifth part of the service</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS List all External References signals ExtRef belonging to an IED and LDevice.inst of an SCD file" href="https://gopro-tickets.rte-france.com/browse/RSR-81" data-issue-key="RSR-81"><del>RSR-81</del></a>&nbsp;has already been developed to extract all attributes of an ExtRef signal</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS : Create a new or overwrite an existing DataSet" href="https://gopro-tickets.rte-france.com/browse/RSR-20" data-issue-key="RSR-20"><del>RSR-20</del></a>&nbsp;has already been developed to create a new DataSet with all its FCDA</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS : Create a new Control Block linked to a DataSet - 1. GOOSE Control Block" href="https://gopro-tickets.rte-france.com/browse/RSR-245" data-issue-key="RSR-245"><del>RSR-245</del></a>&nbsp;has already been developed to create a GOOSE Control Block</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS : Create a new Control Block linked to a DataSet - 2. Sampled Value Control Block" href="https://gopro-tickets.rte-france.com/browse/RSR-253" data-issue-key="RSR-253"><del>RSR-253</del></a>&nbsp;has already been developed to create a SMV Control Block</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS : Create a new Control Block linked to a DataSet - 3. Report Control Block" href="https://gopro-tickets.rte-france.com/browse/RSR-255" data-issue-key="RSR-255"><del>RSR-255</del></a>&nbsp;has already been developed to create a Report Control Block</li>
<li>US&nbsp;<a class="issue-link" title="COMPAS Write the binding of a given External Reference signal (ExtRef.desc) with Control Block into current SCD file" href="https://gopro-tickets.rte-france.com/browse/RSR-93" data-issue-key="RSR-93"><del>RSR-93</del></a>&nbsp;has already been developed to create ExtRef.srcXXX attributes</li>
</ul>
<p>&nbsp;</p>
<p><strong>The inputs</strong>&nbsp;of this service are:</p>
<ul>
<li>The same context that US&nbsp;<a class="issue-link" title="COMPAS - Automated process for Dataset and CB creation and ExtRef update - The previously created Data groups are analysed to be processed or rejected - Part 5/6" href="https://gopro-tickets.rte-france.com/browse/RSR-607" data-issue-key="RSR-607">RSR-607</a> because it is the part 5 of 6 of this COMPAS service US</li>
</ul>
<p>&nbsp;</p>
<p><strong>Description:</strong></p>
<p>For each GOOSE and SV Control Block in current SCD file:</p>
<ul>
<li>Define the:
<ul>
<li>CB name</li>
<li>IED@name</li>
<li>AccessPoint@name</li>
<li>LDevice@inst</li>
<li>where the CB resides into the SCD file</li>
</ul>
</li>
<li>With the Privates of the IED where the CB resides, define:
<ul>
<li>System Version to which it belongs</li>
<li>IED type</li>
<li>IED redundancy</li>
<li>IED instance if existing</li>
<li>if the CB signal is Internal or External to the bay</li>
</ul>
</li>
<li>With the help of the settings file in attachement, with the sextuplet (Control Block Type, the System Version X.Y.Z.W, IED type, IED Redundancy, IED instance if existing, if the CB signal is Bay Internal or External), define the network properties of the CB such as:</li>
</ul>
<ul>
<li>
<ul>
<li>VLAN-ID (in hexadecimal format)</li>
<li>VLAN-PRIORITY</li>
<li>MinTime</li>
<li>MaxTime</li>
<li>The APPID range to which the APPID of the CB has to belong&nbsp;</li>
<li>The MAC Address range to which the MAC Address of the GOOSE CB has to belong&nbsp;
<ul>
<li>Note: In the settings file, "(empty)" means that we don't create the XML section into the SCL/Communication</li>
</ul>
</li>
<li>If no line matches into the settings file then an error message ERR.04 is returned</li>
</ul>
</li>
<li>Generate one unique APPID in hexadecimal format for the CB according to the range specified. Each CB shall have a unique APPID within the whole SCD file&nbsp;</li>
<li>Generate one unique MAC Address for the CB according to the range specified. Each CB has a unique MAC address within the whole SCD file.
<ul>
<li>If it is impossible to give a valid MAC address for a GOOSE CB i.e there are more than 512 GOOSE CBs in the SCD then an error message ERR.05 is returned</li>
</ul>
</li>
</ul>
<ul>
<li>Find the SCL/Communication/SubNetwork/ConnectedAP where SubNetwork/ConnectedAP@iedName = IED name where CB resides AND SubNetwork/ConnectedAP@apName = IED/AccessPoint@name where CB resides
<ul>
<li>If there is NO matching SCL/Communication/SubNetwork/ConnectedAP for the CB then an error message ERR.06 is returned</li>
</ul>
</li>
<li>Then at this place, create:
<ul>
<li>in the case of GOOSE CB, the SCL/Communication/SubNetwork/ConnectedAP/GSE XML section with all the settings values defined in the previous stages. The template of this XML section is given in Details chapter</li>
<li>in the case of SV CB, the SCL/Communication/SubNetwork/ConnectedAP/SMV XML section with all the settings values defined in the previous stages. The template of this XML section is given in Details chapter</li>
</ul>
</li>
<li>The service lists all the errors if any and stops at the end when at least one error is encountered</li>
</ul>
<p>&nbsp;</p>
<p><strong>Details:</strong></p>
<ul>
<li>A GOOSE CB is characterized by the XML tag GSEControl in this kind of XPath SCL/IED@name/AccessPoint@name/LDevice@Inst/LN(0)/GSEControl@name</li>
<li>The GOOSE CB name is given by GSEControl@name</li>
<li>A SV CB is characterized by the XML tag SampledValueControl in this kind of XPath SCL/IED@name/AccessPoint@name/LDevice@Inst/LN(0)/SampledValueControl@name</li>
<li>The SV CB name is given by SampledValueControl@name</li>
<li>The IED System Version is given by the IED/Private@type="COMPAS-SystemVersion"/compas:SystemVersion @MainSystemVersion (i.e X.Y) @MinorSystemVersion (i.e Z.W.V).
<ul>
<li><ins>Note</ins>: To get the X.Y.Z.W system version, remove the V value</li>
<li>If the Private compas:SystemVersion is not found</li>
<li>OR if MainSystemVersion OR MinorSystemVersion attributes are not found</li>
<li>OR if MainSystemVersion OR MinorSystemVersion attributes are not populated</li>
<li>then an error message ERR.01 is returned</li>
</ul>
</li>
<li>The IED type is given by the IED/Private@type="COMPAS-ICDHeader"/compas:ICDHeader @IEDType</li>
<li>The IED redundancy is given by the IED/Private@type="COMPAS-ICDHeader"/compas:ICDHeader @IEDredundancy</li>
<li>The IED instance is given by the IED/Private@type="COMPAS-ICDHeader"/compas:ICDHeader @IEDInstance
<ul>
<li>If the Private compas:ICDHeader is not found</li>
<li>OR if IEDType OR IEDredundancy OR IEDInstance attributes are not found</li>
<li>OR if IEDType OR IEDredundancy OR IEDInstance attributes are not populated</li>
<li>then an error message ERR.02 is returned</li>
</ul>
</li>
<li>The fact that a CB signal is Bay internal or external is given by the last character of the CB@name:
<ul>
<li>if the last character is "I" then the CB signal is Bay Internal</li>
<li>if the last character is "E" then the CB signal is Bay External</li>
<li>If the last character of the CB name is not an "E" OR "I" then an error message is returned ERR.03</li>
</ul>
</li>
<li>The SCL/Communication/SubNetwork/ConnectedAP/GSE XML section template is:
<ul>
<li>&lt;GSE ldInst="<em>LDevice.inst_where_CB_resides</em>" cbName="<em>GOOSE_CB_Name</em>"&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp;&lt;Address&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;P type="VLAN-PRIORITY"&gt;<em>value_from_settings_file</em>&lt;/P&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;P type="APPID"&gt;<em>generated_value</em>&lt;/P&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;P type="MAC-Address"&gt;<em>generated_value</em>&lt;/P&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;P type="VLAN-ID"&gt;<em>hexadecimal_value</em>&lt;/P&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp;&lt;/Address&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp;&lt;MinTime unit="s" multiplier="m"&gt;<em>value_from_settings_file</em>&lt;/MinTime&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp;&lt;MaxTime unit="s" multiplier="m"&gt;<em>value_from_settings_file</em>&lt;/MaxTime&gt;&lt;/GSE&gt;</li>
</ul>
</li>
<li>The SCL/Communication/SubNetwork/ConnectedAP/SMV XML section template is:
<ul>
<li>&lt;SMV ldInst="<em>LDevice.inst_where_CB_resides</em>" cbName="<em>SV_CB_Name</em>"&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp;&lt;Address&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;P type="VLAN-PRIORITY"&gt;<em>value_from_settings_file</em>&lt;/P&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;P type="APPID"&gt;<em>generated_value</em>&lt;/P&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;P type="MAC-Address"&gt;<em>generated_value</em>&lt;/P&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;P type="VLAN-ID"&gt;<em>hexadecimal_value</em>&lt;/P&gt;<br />&nbsp; &nbsp; &nbsp; &nbsp;&lt;/Address&gt;<br />&nbsp;&lt;/SMV&gt;</li>
</ul>
</li>
<li>For a given SCL/Communication/SubNetwork/ConnectedAP, the GSE XML sections are placed before SMV XML sections</li>
</ul>
<p>&nbsp;</p>
<p><strong>Output:</strong></p>
<ul>
<li>For each GOOSE CB, one SCL/Communication/SubNetwork/ConnectedAP/GSE XML section is created with all the properties and settings values defined in the previous stages:
<ul>
<li>GSE@ldInst</li>
<li>GSE@cbName</li>
<li>GSE/Address/P@type="VLAN-PRIORITY" Value</li>
<li>GSE/Address/P@type="APPID" Value</li>
<li>GSE/Address/P@type="MAC-Address" Value</li>
<li>GSE/Address/P@type="VLAN-ID" Value</li>
<li>GSE/MinTime@unit="s" @multiplier="m" Value</li>
<li>GSE/MaxTime@unit="s" @multiplier="m" Value</li>
</ul>
</li>
<li>For each SV CB, one SCL/Communication/SubNetwork/ConnectedAP/SMV XML section is created with all the properties and settings values defined in the previous stages:
<ul>
<li>SMV@ldInst</li>
<li>SMV@cbName</li>
<li>SMV/Address/P@type="VLAN-PRIORITY" Value</li>
<li>SMV/Address/P@type="APPID" Value</li>
<li>SMV/Address/P@type="MAC-Address" Value</li>
<li>SMV/Address/P@type="VLAN-ID" Value</li>
</ul>
</li>
</ul>
<p>&nbsp;</p>
<p><strong>Error messages:</strong></p>
<p>ERR.01: "The COMPAS-SystemVersion Private is not defined for the CB SCL/IED=<em>IED@name</em>/AccessPoint=<em>AccessPoint@name/</em>LDevice=<em>LDevice@inst</em>/LN=<em>LN@prefix @lnClass @inst</em>/CB=<em>CB@name</em>"</p>
<p>&nbsp;</p>
<p>ERR.02: "The COMPAS-ICDHeader Private is not defined for the CB SCL/IED=<em>IED@name</em>/AccessPoint=<em>AccessPoint@name/</em>LDevice=<em>LDevice@inst</em>/LN=<em>LN@prefix @lnClass @inst</em>/CB=<em>CB@name</em>"</p>
<p>&nbsp;</p>
<p>ERR.03: "Unable to determine if the signal is Bay Internal or External for the CB SCL/IED=<em>IED@name</em>/AccessPoint=<em>AccessPoint@name/</em>LDevice=<em>LDevice@inst</em>/LN=<em>LN@prefix @lnClass @inst</em>/CB=<em>CB@name</em> because its last character name is not a "E" or "I""</p>
<p>&nbsp;</p>
<p>ERR.04: "The sextuplet (CBType=<em>Control Block Type</em>, X.Y.Z.W=<em>the System Version X.Y.Z.W,</em> IEDType=<em>IED type,</em> IEDRedundancy=<em>IED Redundancy,</em> IEDInstance=<em>IED instance if existing, if the CB signal is Bay Internal or External</em> ) doesn't match with one and only one line of the settings file"</p>
<p>&nbsp;</p>
<p>ERR.05: "There are too much GOOSE CB in current SCD file to give a unique MAC Address which stays in the range allowed"</p>
<p>&nbsp;</p>
<p>ERR.06: "There is no matching SCL/Communication/SubNetwork/ConnectedAP with the right @iedName and @apName for the CB SCL/IED=<em>IED@name</em>/AccessPoint=<em>AccessPoint@name/</em>LDevice=<em>LDevice@inst</em>/LN=<em>LN@prefix @lnClass @inst</em>/CB=<em>CB@name</em>"</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><ins>Acceptance Criteria:</ins></p>
<ul>
<li>Check that each GOOSE CB owns in the SCL/Communication Path, a GSE XML section placed in the SubNetwork/ConnectedAP where:
<ul>
<li>ConnectedAP@iedName = IED@name where resides the CB</li>
<li>ConnectedAP@apName = AccessPoint@name where resides the CB</li>
</ul>
</li>
<li>Check that each GSE XML section has the following attributes:
<ul>
<li>GSE@ldInst = IED/LDevice@inst where resides the CB</li>
<li>GSE@cbName = CB name
<ul>
<li>GSE/Address/P@Type="VLAN-PRIORITY" value = value given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
<li>GSE/Address/P@Type="VLAN-ID" value = value given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
<li>GSE/Address/P@Type="APPID" value = unique value generated in hexadecimal format according to the range given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
<li>GSE/Address/P@Type="MAC-Address" value = unique value generated according to the range given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
<li>GSE/MinTime@unit="s" @multiplier="m" value = value given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
<li>GSE/MaxTime@unit="s" @multiplier="m" value = value given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
</ul>
</li>
</ul>
</li>
<li>Check that each SampledValue CB&nbsp;has the following attributes:
<ul>
<li>SMV@ldInst = IED/LDevice@inst where resides the CB</li>
<li>SMV@cbName = CB name
<ul>
<li>SMV/Address/P@Type="VLAN-PRIORITY" value = value given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
<li>SMV/Address/P@Type="VLAN-ID" value = value given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
<li>SMV/Address/P@Type="APPID" value = unique value generated in hexadecimal format according to the range given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
<li>SMV/Address/P@Type="MAC-Address" value = unique value generated according to the range given by the settings file for the corresponding sextuplet (CB Type, the X.Y.Z.W, IEDType, IEDRedundancy, IED instance if existing, if the CB signal is Bay Internal or External)</li>
</ul>
</li>
</ul>
</li>
<li>Check that if the COMPAS-SystemVersion Private is not defined for the IED where resides the CB then an error message is returned</li>
<li>Check that if the COMPAS-ICDHeader Private is not defined for the IED where resides the CB then an error message is returned</li>
<li>Check that if the service can't determine whether the CB signal is Bay internal or external then an error message is returned</li>
<li>Check that if there is no or more than one matching line(s) with the settings file for one sextuplet (CBType=<em>Control Block Type</em>, X.Y.Z.W=<em>the System Version X.Y.Z.W,</em>&nbsp;IEDType=<em>IED type,</em>&nbsp;IEDRedundancy=<em>IED Redundancy,</em>&nbsp;IEDInstance=<em>IED instance if existing, if the CB signal is Bay Internal or External</em>) then an error message is returned</li>
<li>Check that if there are too much GOOSE CB in current SCD file to give a unique MAC Address which stays in the range allowed then an error message is returned</li>
<li>Check that if there is no matching SCL/Communication/SubNetwork/ConnectedAP with the right @iedName and @apName for the CB then an error message is returned</li>
<li>Check that this service computes the whole SCD file and returns all encountered errors i.e it doesn't stop at the first error encountered</li>
<li>Check that if at least one error is encountered during the processing of the whole SCD file then the service stops</li>
</ul>
<p>&nbsp;</p>

</body>
</html>

**Comment by DamienPERNET** [comment]
[RCONF_CB_COMMUNICATION_20221213.xlsx](https://github.com/com-pas/compas-sct/files/10536810/RCONF_CB_COMMUNICATION_20221213.xlsx)

**Comment by massifben** [comment]
Re-opening this issue to update the interface of the service: 
- 1 single method for configuring GOOSE and SMV at the same time
- this method will have 3 parameters : 
  - scd
  - function implementing ControlBlockNetworkSettings (provides vlanId, vlanPriority, minTime and maxTime)
  - record that provide appID and macAddress ranges for GOOSE and SMV
