### ISSUE TITLE
EPIC RSR-51 / RSR-60 S79 : Add new IEDs

### ISSUE THREAD

**Issue by jeanetiennelemaire** [com-pas/compas-sct#3]
As a COMPAS service user, this US (user story) purpose is to import ICD file into predefined SCD file. 

Prerequisites

A input SCD stored in COMPASS BDD. The input SCD file can contain no or many /SCL/IED.

The inputs of this service are:

A previous existing SCD file defined by Header.id, Header.version and Header.revision
An ICD file (required)
New IED.name (required)
A list of (Subnetwork.name, Subnetwork.type, ConnectedAP.name) to link a given ConnectedAP.name of the IED to a Subnetwork.name
The output of this service is an updated SCD file with new SCL/IED, SCL/Communication and SCL/DataTypeTemplate AND a list of /SCL/Communication/SubNetwork/ConnectedAP/Address/P

This US is covering the following functional services as described in the 61850-6:

S11 : import IED data model
S17 : reuse already imported DataTypeTemplates for identical types
S21 : configure (edit) IED name
S25 : configure ldName values ; to be done only if the LDevice.ldName is present as input of the service
S66 : keep type identifiers in DataTypeTemplate section unique even if on ICD import the same ID is used in different ICD files for different type structures.
 

The following steps have to be considered to add a new IED

RSR-6 : Import the /DataTypeTemplates/LNodeType, DOType, DAType, EnumType of the ICD ; if 2 or more DTT have the same id, compare the content of DTT (all attributes of each children have to be considered) (S11 : Import IED data model):
                  Case1) If for the same id, the content is different, rename the ID by a new one. This new ID is generated by concatenating the IED.name , an underscore, and the old ID (to keep track of history). If the new ID is longer than 255 characters, truncate the old ID starting from right so that the new one is less than 255 characters. In that case, the old ID associated to the new ID of LNodeType.id is stored for  use in future US ;

(S66 : Keep type identifiers in DataTypeTemplate section unique even if on ICD import the same ID is used in different ICD files for different type structures)

In case of renaming DOType.id, the new DOType.id is propagated to all DO.name of all LNodeType.id which uses the DOType.id.
In case of renaming DAType.id, the new DAType.id is propagated to all DA.name of all DOType.id which uses the DAType.id.
In case of renaming EnumType.id, the new EnumType.id is propagated to all DA.name of all DOType.id which uses the EnumType.id.
If following, the renaming of the new ID, the new ID is already existing in the SCD file, then the ICD file is rejected because "One of the DTT is already existing with ID"
                  Case 2) If for the same id, the content is strictly identical (order of children in DTT shall be considered), keep only one DTT (S17 : reuse already imported DataTypeTemplates for identical types)

                  Case3) If for the same content, the ids are different, keep the ids and import several DTT.

RSR-60 : Import /IED node and all associated children from ICD file into SCD file for a defined IED.name. If existing, the old LNodeType.id and new LNodeType.id provided by RSR-6 are input in this US.
RSR-62 : For each Subnetwork.name defined in input, if doesn't exist create the Subnetwork.name for a given SubNetwork.type (8-MMS or IP). If the Subnetwork.name does exist do nothing (defined as independent service)
RSR-64 : Within a defined Subnetwork.name, import from ICD the connectedAP.name with children elements into SCD file in each given SCL/Communication/Subnetwork.name defined in input:
If the SubNetwork.type and name already exists, insert into this SubNetwork the <ConnectedAP at the end of the ConnectedAP previous blocks
Else create the new SubNetwork.name block with its type and name then insert the <ConnectedAP blocks into this new SubNetwork.name
      

Extract from 61850-6 p121

An SCT may be required to change the id of an LnodeType, DOType, DAType or EnumType but it is not allowed to change the underlying structure.
All types are uniquely identified by their type id. On generation of the system SCD file from IED ICD files, the LN type identifications may have to change to keep uniqueness across all IED definitions. To keep possible semantic information of the type names, it is recommended to generate a new LN type name by concatenating the IED name (which shall be unique within the file) with the old LNodeType name (which shall be unique at least per IED).

**Comment by Sander3003** [comment]
What is meant by the CoMPAS BDD and DTT?

**Comment by jeanetiennelemaire** [comment]
Hi, the DTT stands for DataTypeTemplates and sorry for the french acronym BDD which stands for DataBase.
