### ISSUE TITLE
[RSR-886]: LDEPF service uses the XML settings file

### ISSUE THREAD

**Issue by samirromdhani** [com-pas/compas-sct#345]
**User Story**

As we've moved to using XML settings file, this issue represents an upgrade for the LDEPF service to use XML structure as an alternative to CSV files.

**Comment by samirromdhani** [comment]
Related to https://github.com/com-pas/compas-sct/issues/256

**Comment by YohanHamel** [comment]
[XSD_LDEPF_Config_file_v2.zip](https://github.com/com-pas/compas-sct/files/13438376/XSD_LDEPF_Config_file_v2.zip)

Hi, here is the related XSD file.
