### ISSUE TITLE
RSR-926 Remove name restriction on AccessPoint@name

### ISSUE THREAD

**Issue by rahmananica** [com-pas/compas-sct#373]
**User Story**

Inputs:
- SCD file 

### US process description:

As the automated process of SCD generation imports STDs, the AccessPoint@name shouldn't be verified. 
ConnectedAP@apName has a list of names that it can accept. By this enhancement, the process should allow any name and not only those mentioned in the list. 

Enhancement #66

**Comment by samirromdhani** [comment]
https://github.com/com-pas/compas-sct/pull/372

**Comment by samirromdhani** [comment]
closed 
https://github.com/com-pas/compas-sct/pull/372

**Comment by samirromdhani** [comment]
Done https://github.com/com-pas/compas-sct/issues/373
