### ISSUE TITLE
COMPAS UPDATE RSR-1048 - Key management for LDEPF binding

### ISSUE THREAD

**Issue by hkaroun** [com-pas/compas-sct#412]
_**User Story**_
DIGITAL inputs are characterized in LDEPF by InRef which have a @purpose  DYN_LDEPF_DIGITAL CHANNEL 36_1_BOOLEAN (example).

However, at ExtRef level, you can have a Boolean but also an Enum. Example: DYN_LDEPF_DIGITAL CHANNEL 36_1_FaultDirectionKind_13_dirGeneral_1

If you bind the ExtRef as described above, the process that binds the InRef will be unable to make the association between the InRef and the ExtRef, as we won't have the same character string.

An exception will have to be made when updating the InRef for all DIGITAL CHANNEL functions. For example, "DYN_LDEPF_DIGITAL CHANNEL 36_1" and no longer "DYN_LDEPF_DIGITAL CHANNEL 36_1_BOOLEAN".

**As** a the InRef update process

**When** we are linking InRef and ExtRef

**So** a shortened key will have to be used to enable correspondence between InRef and ExtRef

_**Acceptance criteria**_

Check that during the InRef update process, the key used to match the InRef to the Extref is shortened so that there is a match.

**Comment by samirromdhani** [comment]
Linked to #231
