### ISSUE TITLE
EPIC RSR-51 / RSR-6 / RSR-232 : S79 : Add DataTypeTemplates from ICD to current SCD

### ISSUE THREAD

**Issue by jeanetiennelemaire** [com-pas/compas-sct#5]
As a COMPAS service user, this US (user story) purpose is to import ICD DataTypeTemplate into predefined SCD file.

The inputs of this service are:

A previous existing SCD file defined by Header.id, Header.version and Header.revision (required)
An ICD file (required)
IED.name
Prerequisite : the IED.name not already exists in the SCD file

This US is covering the following functional services as described in the 61850-6:

S11 : import IED data model
S17 : reuse already imported DataTypeTemplates for identical types
S66 : keep type identifiers in DataTypeTemplate section unique even if on ICD import the same ID is used in different ICD files for different type structures.
 The following steps have to be considered to import ICD DataTypeTemplate :

Import the /DataTypeTemplates/LNodeType, DOType, DAType, EnumType of the ICD ; if 2 or more DTT have the same id, compare the content of DTT (all attributes of each children have to be considered) (S11 : Import IED data model):
                  Case1) If for the same id, the content is different, rename the ID by a new one. This new ID is generated by concatenating the IED.name , an underscore, and the old ID (to keep track of history). If the new ID is longer than 255 characters, truncate the old ID starting from right so that the new one is less than 255 characters. In that case, a Private is added as a children of the /DataTypeTemplates/LNodeType as  /DataTypeTemplates/LNodeType/Private.type="COMPAS_OLD_ID" ; the node value is defined as the old ID of the concerned LNodeType.

(S66 : Keep type identifiers in DataTypeTemplate section unique even if on ICD import the same ID is used in different ICD files for different type structures)

If following, the renaming of the new ID, the new ID is already existing in the SCD file, check the content of the two LNodeType, DOType, DAType and EnumType :
If the content are strictly identical, then do not add the new LNodeType or DOType, or DAType or EnumType and go next to LNodeType to be imported
Elseif the two LNodeType or DOType, or DAType or EnumType have different content, the ICD file is rejected with the error message "One of the DTT is already existing with the same ID but different content"
In case of renaming DOType.id, the new DOType.id is propagated to
All DO.name of all LNodeType.id which uses the DOType.id.
All SDO.name of all DOType which uses the DOType.id.
In case of renaming DAType.id, the new DAType.id is propagated to all
DA.name of all DOType.id which uses the DAType.id.
BDA.name of all DAType which uses the DAType.id.
In case of renaming EnumType.id, the new EnumType.id is propagated to all :
DA.name of all DOType.id which uses the EnumType.id.
BDA.name of all DAType which uses the EnumType.id.
                  Case 2) If for the same id, the content is strictly identical (order of children in DTT shall be considered), keep previous already imported DTT and do not import new one (S17 : reuse already imported DataTypeTemplates for identical types)

                  Case3) If for the same content, the ids are different, keep the ids and import several DTT.

**General rules to define if two DTT are different**

- In LNodeType, the order of DO.name node are not considered in the comparison ; as a consequence, same DO node but with different order will be considered as the same LNodeType.
- In DOType, the order of SDO.name and DA.name are defined by the norm and has to be respected.
- In DAType, the order of BDA.name are defined by the norm and has to be respected.
- In EnumType, the order of EnumVal are defined by the norm and has to be respected.
- In all kind of objects, the private sub nodes are not part of the comparison. This happen if xml fragments are in the Privates.

**For each DTT, the following attributes considers whether if two DTT are considered identical**

For LNodeType :

- LNodeType.id
- LNodeType.lnClass
- LNodeType.iedType
- DO.name
- DO.type
- DO.accessControl
- DO.transient

For DOType :

- DOType.id
- DOType.cdc
- DOType.iedType 
- SDO.name
- SDO.type
- SDO.count
- DA.name
- DA.fc
- DA.dchg
- DA.qchg
- DA.dupd
- DA.sAddr
- DA.bType
- DA.valKind
- DA.type
- DA.count
- DA.valImport
- DA.Val (value of the node)
- DA.Val.sGroup
- DA.ProtNs (value of the node)
- DA.ProtNs.type

For DAType :

- DAType.iedType
- DAType.id
- BDA.name
- BDA.sAddr
- BDA.valKind
- BDA.valImport
- BDA.type
- BDA.bType
- BDA.count
- BDA.Val (value of the node)
- BDA.Val.sGroup
- ProtNs (value of the node)
- ProtNs.type

For EnumType,

- EnumType.id
- EnumVal (value of the node)
- EnumVal.ord
 

As output, the service:

Store and replace the new SCD file in COMPAS BDD
Extract from 61850-6 p121

An SCT may be required to change the id of an LnodeType, DOType, DAType or EnumType but it is not allowed to change the underlying structure.
All types are uniquely identified by their type id. On generation of the system SCD file from IED ICD files, the LN type identifications may have to change to keep uniqueness across all IED definitions. To keep possible semantic information of the type names, it is recommended to generate a new LN type name by concatenating the IED name (which shall be unique within the file) with the old LNodeType name (which shall be unique at least per IED).

**Comment by Sander3003** [comment]
Looks good to me. Suggestion: consider using (header) history options to keep track of the changes.

**Comment by jeanetiennelemaire** [comment]
Merge RSR-6 and RSR-232
