### ISSUE TITLE
EPIC RSR-51 / RSR-60 : Add a new IED from ICD to current SCD

### ISSUE THREAD

**Issue by jeanetiennelemaire** [com-pas/compas-sct#7]
As a COMPAS service user, this US purpose is to import IED from ICD file into predefined SCD file.

**Prerequisites**

/SCL/DataTypeTemplates have already been imported in current SCD file
ICD file is compliant with SCL XSD.
The IED.name not already exists in the SCD file
 The inputs of this service are:

A previous existing SCD file (required) defined by Header.id, Header.version and Header.revision
An ICD file (required)
LNodeType.id and associated old LNodeType.id (optional)
The IED.name of the IED.name to import (required)
Goal of the US

**The goal is to**

- Copy the whole /SCL/IED XML block from the ICD file into the SCD file ; the following change have to be done if any /SCL/DataTypeTemplates/LNodeType.id is associated to a old LNodeType.id then replace all the old LNodeType.id in 
- /SCL/IED/AccessPoint/Server/LDevice/LN0.lnType 
- And /SCL/IED/AccessPoint/Server/LDevice/LN.lnType 
- By the new LNodeType.id defined in the /SCL/DataTypeTemplates/LNodeType.id where the associated old id resides.
- 
- If there is no LNodeType.id associated to old LNodeType.id nothing is changed
- Replace existing /SCL/IED.name value by the IED.name specified as input. The concatenation of /SCL/IED.name and /SCL/IED/AccessPoint/Server/LDevice.inst for each LDevice.inst of this IED has to be less than 33 characters. Else abord the whole process and display an error.
- Rename all SCL/IED/AccessPoint/Server/LDevice.ldName = concatenation of IED.nameLDevice.inst

 

**Output**

The service update the SCD file in COMPASS BDD
Error

- An error message : "there is no DataTypeTemplates in the current SCD file" if there is no /SCL/DataTypeTemplates node
- 
- An error message : "The DataTypeTemplates LNodeType.id = id the LNodetype.id in the current SCD file is missing" if there is a DataTypeTemplates LNodeType.id which is not existing
- 
- An error message : "ICD is not compliant with SCL XSD"
- 
- An error message : "Concatenation of value of IED.nameLDevice.int is more than 33 characters; process abord"
- 
- An error message : "IED.name is already existing in the current SCD file" if the IED.name have been already previously imported in the same SCD file.
- 
- An error message in case an required attribute is not specified as input : "Expected attribute is required but not defined"

**Comment by Sander3003** [comment]
Looks good to me!
