### ISSUE TITLE
[RSR-416] Bug correction for Issue #9 - The /Communication/SubNetwork/ConnectedAP XML section is imported into SCD file but without its /Address and /PhysConn XML subsections

### ISSUE THREAD

**Issue by DamienPERNET** [com-pas/compas-sct#76]
When we import an ICD file into a SCD file by calling COMPAS service [Issue #9](https://github.com/com-pas/compas-sct/issues/9), the /Communication/SubNetwork/ConnectedAP XML section is imported into SCD file but without its /Address and /PhysConn XML subsections.

 
Obtained result:

The /Communication/SubNetwork/ConnectedAP XML section is imported into SCD file but without its /Address and /PhysConn XML subsections.

Expected result:

The /Communication/SubNetwork/ConnectedAP XML section is imported into SCD file with its /Address and /PhysConn XML subsections (if existing).

**Comment by samirromdhani** [comment]
Related to [#66](https://github.com/com-pas/compas-sct/issues/66)
