### ISSUE TITLE
EPIC RSR-51 / RSR-62 : create a new SubNetwork to current SCD

### ISSUE THREAD

**Issue by jeanetiennelemaire** [com-pas/compas-sct#8]
As a COMPAS service user, this US purpose is to create a new SubNetwork into predefined SCD file.

 

As an integrator, I would like to create a new SubNetwork to current SCD if it doesn't exist.

Prerequisites : an existing SCD file which exists in COMPAS BDD

 

The inputs of this service are:

A previous existing SCD file (Mandatory) defined by Header.id, Header.version and Header.revision
The SubNetwork.name to create or configure (Mandatory)
The SubNetwork.type to create or configure (Optional), it shall only contain "8-MMS", "IP" or "PHYSICAL" values
  

This US is covering the first part of the following functional service as described in the 61850-6:

S22 Create and configure SubNetworks and IED communication addresses
 

 The following steps have to be considered to create a new SubNetwork XML block into the SCD file:

If for the given SubNetwork.name as input, an occurrence already exists in the XPath /SCL/Communication/SubNetwork@name in the SCD file, then the SubNetwork is not created. Indeed, the /SCL/Communication/SubNetwork@name shall be unique within a SCD file.
If, for the provided SubNetwork.name, there is not a SubNetwork with that name in the SCD file, then a new SubNetwork block is created into the SCD file. This new block is inserted with its attributes "name" (mandatory) and "type" (optional) into the /SCL/Communication section and just after the last SubNetwork block if exists. The SubNetwork block attributes are filled with their values. 
Output

The output of the service is an updated SCD file with a new Subnetwork.name

Error

If the the /SCL/Communication/SubNetwork@name is already existing in the SCL file display the error message "The subnetwork have not been created because already existing in the SCD file"

**Comment by Sander3003** [comment]
Looks good to me
