### ISSUE TITLE
EPIC RSR-51 / RSR-64 : Associate a list of Connected Access Point (ConnectedAP) to a SubNetwork

### ISSUE THREAD

**Issue by jeanetiennelemaire** [com-pas/compas-sct#9]
As a COMPAS service user, this US purpose is to associate Connected Access Points (ConnectedAP) of an IED with a SubNetwork.

As service user, from the list of selected name and iedName of the Connected Access Points ( i.e all couples (ConnectedAP.apName, ConnectedAP.iedName)) that are in the ICD file of the IED, I want to associate my selection of Connected Access Points with a given SubNetwork already defined in SCD file.

Prerequisites : an SCD file is already existing and contains at least one /SCL/IED.name with associated /DataTypeTemplates and one /SCL/Communication/SubNetwork.name which can be empty or not.

The inputs of this service are:

A previous existing SCD file (Mandatory) defined by Header.id, Header.version and Header.revision
An ICD file from where the selected ConnectedAP.name will be imported
The IED.name for which the /SCL/Communication/SubNetwork/ConnectedAP will be imported.
A list of connected Access Points with target Subnetwork.name (Subnetwork.name, ConnectedAP.apName, ConnectedAP.iedName=IED.name)
This US is covering the third part of the following functional service as described in the 61850-6:

S22 Create and configure SubNetworks and IED communication addresses
 

The following steps have to be considered to associate a Connected Access Point, i.e a couple (ConnectedAP.apName, ConnectedAP.iedName), by insertion in the given SubNetwork.name of a SCD file:

For each selected Connected Access Points (Subnetwork.name, ConnectedAP.apName, ConnectedAP.iedName), check that (ConnectedAP.apName, ConnectedAP.iedName) of the ICD are not already present in the SubNetwork.name of the SCD file:
If a couple (ConnectedAP.apName, ConnectedAP.iedName) is already present, display an error and process the next ConnectedAP.apName
else copy from /SCL/Communication/SubNetwork/ConnectedAP XML block (include subchildren elements see bellow) from ICD file WHERE ConnectedAP.apName = ConnectedAP.name defined in the input TO SCD file /SCL/Communication/SubNetwork WHERE Subnetwork.name of SCD file = value of Subnetwork.name defined as input AND /SCL/Communication/SubNetwork/ConnectedAP.iedName = IED.name defined as input; only the 
/SCL/Communication/SubNetwork/ConnectedAP/Address
And /SCL/Communication/SubNetwork/ConnectedAP/PhysConn if exists
SCL/Communication/SubNetwork/ConnectedAP/GSE and SCL/Communication/SubNetwork/ConnectedAP/SMV XML blocks must be excluded if exists
The uniqueness of the (ConnectedAP.apName, ConnectedAP.iedName) within its SubNetwork.name is defined by XSD verification
If yes commit the change into SCD file.
If not do no commit change into SCD file, reject ICD file and output an error message "The connectedAP.apName = valeur of the connectedAP.apName, ConnectedAP.iedName = value of the ConnectedAP.iedName"
The output of the service

An updated SCD file with added ConnectedAP copied from ICD file OR an error message if the connectedAP.apName, ConnectedAP.iedName is already existing in the Subnetwork.name = value of the Subnetwork.name

**Comment by Sander3003** [comment]
Looks good to me!
